name = "himin"
description = "A minimal and clean theme for Hugo."
features = ["blog", "shortcode", "syntax Highlighting"]
homepage = "https://github.com/saliei/hugo-theme-himin/"
license = "MIT"
licenselink = "https://github.com/saliei/hugo-theme-himin/blob/master/LICENSE.md"
min_version = 0.90
tags = [
  "blog",
  "clean",
  "customizable",
  "dark",
  "highlighting",
  "light",
  "minimal",
  "monochromatic",
  "multilingual",
  "personal",
  "responsive",
  "simple",
  "technical",
]

[author]
homepage = "https://saliei.com"
name = "saliei"
